# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverpage', models.FileField(upload_to='')),
                ('pagename', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='PageName',
        ),
    ]
