# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_userpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedetail',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageDetail',
        ),
    ]
