# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170114_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='user',
        ),
        migrations.AddField(
            model_name='userpage',
            name='user',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
