# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170117_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='check1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('cover_page', models.FileField(upload_to='')),
            ],
        ),
    ]
