# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170117_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check1',
        ),
    ]
