# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_delete_check1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='cover_page',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='user',
        ),
        migrations.AddField(
            model_name='userpage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
