# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20170117_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userpage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.UserPage'),
            preserve_default=False,
        ),
    ]
