# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_post_userpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='category',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
