# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
