# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20170407_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
